// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.exchanges.domain;

import java.lang.String;

privileged aspect Website_Roo_JavaBean {
    
    public String Website.getUrl() {
        return this.url;
    }
    
    public void Website.setUrl(String url) {
        this.url = url;
    }
    
}
